# constat:template id=elixir-mix-mutation version=24 sha256=c16dae244e4da777a1edb4d469b0c4a9b64e6490be7494ba1b7ab5595c4d1da4
# Generated by Constat's onboarding pull request. Produces the "constat-check-report-mutation"
# workflow artifact: does a check that runs a line this change added or altered actually NOTICE
# that line being wrong? Only ever mutates lines this change's own diff introduced — nothing
# outside it is ever touched, however long the run goes — and every mutant's edit is reverted
# before the next one is even planned.
#
# Usage: elixir constat-mix-mutation.exs <base-ref> <outputFile>
#   env MUTATION_MAX_MUTANTS    (default 6)   — the mutant-count cap.
#   env MUTATION_BUDGET_SECONDS (default 240) — the wall-clock cap for the whole mutation loop.

[base_ref, output_file] = System.argv()
max_mutants = String.to_integer(System.get_env("MUTATION_MAX_MUTANTS", "6"))
budget_ms = String.to_integer(System.get_env("MUTATION_BUDGET_SECONDS", "240")) * 1000
test_file_re = ~r/(^|\/)test\/.*_test\.exs$/
source_file_re = ~r/\.exs?$/

q = <<34>>
json_string = fn value ->
  escaped =
    value
    |> to_string()
    |> String.replace(<<92>>, <<92, 92>>)
    |> String.replace(q, <<92>> <> q)
    |> String.replace(<<10>>, "\\n")

  q <> escaped <> q
end

run = fn cmd, args ->
  System.cmd(cmd, args, stderr_to_stdout: true)
end

# ---- 1. Which lines did this change add or alter? Git's own diff, never a wider scan. ----

{_out, 0} = run.("git", ["fetch", "--no-tags", "origin", base_ref])
{merge_base, 0} = run.("git", ["merge-base", "FETCH_HEAD", "HEAD"])
merge_base = String.trim(merge_base)
{name_status, 0} = run.("git", ["diff", "--name-status", "--diff-filter=ACMR", merge_base, "HEAD"])

changed_files =
  name_status
  |> String.split("\n", trim: true)
  |> Enum.map(fn line -> line |> String.split("\t") |> List.last() end)

hunk_header = ~r/^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/

added_lines = fn patch ->
  patch
  |> String.split("\n")
  |> Enum.reduce({[], 0, false}, fn raw, {lines, new_line, in_hunk} ->
    cond do
      Regex.run(hunk_header, raw) ->
        [_, start] = Regex.run(hunk_header, raw)
        {lines, String.to_integer(start), true}

      not in_hunk ->
        {lines, new_line, in_hunk}

      String.starts_with?(raw, "+++") ->
        {lines, new_line, in_hunk}

      String.starts_with?(raw, "+") ->
        {[new_line | lines], new_line + 1, in_hunk}

      String.starts_with?(raw, "---") ->
        {lines, new_line, in_hunk}

      String.starts_with?(raw, "-") ->
        {lines, new_line, in_hunk}

      String.starts_with?(raw, "\\\\") ->
        {lines, new_line, in_hunk}

      true ->
        {lines, new_line + 1, in_hunk}
    end
  end)
  |> elem(0)
  |> Enum.reverse()
end

changed_lines =
  for file <- changed_files,
      file not in [nil, ""],
      Regex.match?(source_file_re, file),
      not Regex.match?(test_file_re, file),
      File.exists?(file),
      into: %{} do
    {_out, 0} = run.("git", ["fetch", "--no-tags", "origin", base_ref])
    {patch, 0} = run.("git", ["diff", "--unified=0", merge_base, "HEAD", "--", file])
    {file, MapSet.new(added_lines.(patch))}
  end
  |> Enum.filter(fn {_file, lines} -> MapSet.size(lines) > 0 end)
  |> Map.new()

# ---- 2. Which of those lines does this script know how to break? ----

operators = [
  {"===", "!=="}, {"!==", "==="}, {"==", "!="}, {"!=", "=="},
  {">=", "<"}, {"<=", ">"}, {"&&", "||"}, {"||", "&&"}, {" and ", " or "}, {" or ", " and "},
]

comment_only? = fn line ->
  trimmed = String.trim(line)
  trimmed == "" or String.starts_with?(trimmed, "#")
end

describe_mutation = fn line ->
  cond do
    comment_only?.(line) ->
      nil

    true ->
      operator_hit =
        Enum.find_value(operators, fn {from, to} ->
          if String.contains?(line, from) do
            mutated = String.replace(line, from, to, global: false)
            if mutated != line, do: {"inverted the operator: '#{String.trim(from)}' became '#{String.trim(to)}'", mutated}
          end
        end)

      cond do
        operator_hit ->
          {desc, mutated} = operator_hit
          %{description: desc, mutated: mutated}

        Regex.match?(~r/^\s*(true|false)\s*$/, line) ->
          flipped = if String.trim(line) == "true", do: "false", else: "true"
          indent = String.duplicate(" ", String.length(line) - String.length(String.trim_leading(line)))
          %{description: "flipped a fixed boolean return value", mutated: indent <> flipped}

        Regex.match?(~r/^\s*(if|unless)\s+.+\s+do\s*$/, line) and not String.contains?(line, "!") ->
          mutated = Regex.replace(~r/^(\s*)(if|unless)(\s+)(.+?)(\s+do\s*)$/, line, "\\1\\2\\3!(\\4)\\5")
          if mutated != line, do: %{description: "negated the whole condition", mutated: mutated}, else: nil

        true ->
          nil
      end
  end
end

candidates =
  for {file, lines} <- Enum.sort_by(changed_lines, fn {file, _} -> file end),
      text = File.read!(file),
      source_lines = String.split(text, "\n"),
      line_no <- Enum.sort(MapSet.to_list(lines)),
      described = describe_mutation.(Enum.at(source_lines, line_no - 1, "")),
      described != nil do
    %{file: file, line: line_no, description: described.description, mutated: described.mutated}
  end

planned = Enum.take(candidates, max_mutants)

if length(candidates) > length(planned) do
  IO.puts(:stderr, "::warning::#{length(candidates)} mutable line(s) found in this change, capped at #{max_mutants} — #{length(candidates) - length(planned)} will not be attempted this run.")
end

write_report = fn planned_count, attempted, stopped_early, mutants ->
  mutants_json =
    mutants
    |> Enum.map(fn m ->
      checks_json =
        m.checks
        |> Enum.map(fn c ->
          file_json = if c.file, do: json_string.(c.file), else: "null"
          "{" <> q <> "name" <> q <> ": " <> json_string.(c.name) <> ", " <> q <> "status" <> q <> ": " <> json_string.(c.status) <> ", " <> q <> "file" <> q <> ": " <> file_json <> "}"
        end)
        |> Enum.join(", ")

      "{" <> q <> "file" <> q <> ": " <> json_string.(m.file) <> ", " <> q <> "line" <> q <> ": " <> Integer.to_string(m.line) <>
        ", " <> q <> "description" <> q <> ": " <> json_string.(m.description) <> ", " <> q <> "checks" <> q <> ": [" <> checks_json <> "]}"
    end)
    |> Enum.join(",\n    ")

  budget_seconds = div(budget_ms, 1000)

  report =
    "{\n  " <> q <> "schema" <> q <> ": " <> q <> "constat.check-mutation/v1" <> q <>
      ",\n  " <> q <> "plannedMutants" <> q <> ": " <> Integer.to_string(planned_count) <>
      ",\n  " <> q <> "attemptedMutants" <> q <> ": " <> Integer.to_string(attempted) <>
      ",\n  " <> q <> "stoppedEarly" <> q <> ": " <> to_string(stopped_early) <>
      ",\n  " <> q <> "budgetSeconds" <> q <> ": " <> Integer.to_string(budget_seconds) <>
      ",\n  " <> q <> "mutants" <> q <> ": [\n    " <> mutants_json <> "\n  ]\n}\n"

  File.mkdir_p!(Path.dirname(output_file))
  File.write!(output_file, report)
end

if planned == [] do
  write_report.(0, 0, false, [])
  IO.puts("no mutable line found in this change's diff against #{base_ref} — wrote an empty report")
else
  start_ms = System.monotonic_time(:millisecond)

  {mutants, stopped_early} =
    Enum.reduce_while(planned, {[], false}, fn mutant, {acc, _stopped} ->
      if System.monotonic_time(:millisecond) - start_ms >= budget_ms do
        {:halt, {acc, true}}
      else
        original = File.read!(mutant.file)
        lines = String.split(original, "\n")
        mutated_lines = List.replace_at(lines, mutant.line - 1, mutant.mutated)

        checks =
          try do
            File.write!(mutant.file, Enum.join(mutated_lines, "\n"))
            report_path = ".constat/check-report-mutant/checks.json"
            File.rm(report_path)

            System.cmd("mix", ["test"],
              env: [{"CONSTAT_CHECK_REPORT_PATH", report_path}],
              stderr_to_stdout: true
            )

            case File.read(report_path) do
              {:ok, body} ->
                Regex.scan(~r/\{\s*"name":\s*"((?:[^"\\]|\\.)*)",\s*"status":\s*"([a-z_]+)",\s*"file":\s*(null|"((?:[^"\\]|\\.)*)")\s*\}/, body)
                |> Enum.map(fn
                  [_, name, status, "null", _] -> %{name: name, status: status, file: nil}
                  [_, name, status, _, file] -> %{name: name, status: status, file: file}
                end)

              {:error, _} ->
                []
            end
          after
            # Restored before the NEXT mutant is even considered — never left broken across an
            # error, a timeout, or the budget stopping the loop right after this one.
            File.write!(mutant.file, original)
          end

        {:cont, {[%{file: mutant.file, line: mutant.line, description: mutant.description, checks: checks} | acc], false}}
      end
    end)

  mutants = Enum.reverse(mutants)

  # Belt-and-suspenders: confirm the tree this script leaves behind is really clean, the same
  # promise the per-mutant `after` block above already keeps. Never fatal — a mismatch here is
  # louder evidence of a bug in the loop above than a reason to fail the whole job silently.
  {status_out, 0} = run.("git", ["status", "--porcelain"])
  if String.trim(status_out) != "" do
    IO.puts(:stderr, "::warning::working tree not clean after the mutation run — restoring: #{status_out}")
    run.("git", ["checkout", "--", "."])
  end

  write_report.(length(planned), length(mutants), stopped_early, mutants)

  IO.puts(
    "ran #{length(mutants)} of #{length(planned)} planned mutant(s)" <>
      (if stopped_early, do: " (stopped early at the time budget)", else: "") <> " -> #{output_file}"
  )
end
