#!/usr/bin/env bash
# constat:template id=elixir-mix-coverage version=24 sha256=a6f08c93c7a7f2e5ed431b0bea5326adcff6744aae2c47a0ae7943880099084f
# Generated by Constat's onboarding pull request. Produces the "constat-check-coverage"
# workflow artifact: for every ExUnit test file, which lines of which source files it actually
# executed. Runs "mix test <file> --export-coverage <slug>" once per test file — real isolation,
# the same guarantee running each file as its own OS process gives every other ecosystem's
# collector — then hands the raw .coverdata files to constat_coverage_analyze.exs, which turns
# Erlang's own cover data into the same "constat.check-coverage/v1" JSON shape every ecosystem
# writes, so nothing downstream of this script is Elixir-specific at all.
#
# Best-effort by design: a test file whose coverage run fails (a timeout, a compile error) is
# skipped and logged, never fatal to the job — one file's failure must not cost every OTHER
# check's coverage comparison.
#
# Usage: constat-mix-coverage.sh <outputFile>

set -uo pipefail

OUTPUT_FILE="${1:?usage: constat-mix-coverage.sh <outputFile>}"
COVER_DIR="cover"
MANIFEST="$(mktemp)"
trap 'rm -f "$MANIFEST"' EXIT

# Bounds one CI job's runtime: each entry is one extra "mix test" process. Above this, coverage
# degrades to "not published for the rest" rather than let one repository's test count run the job
# for an hour. Every file dropped by the cap is named in the job log — never a silent truncation.
FILE_CAP=300

mkdir -p "$COVER_DIR"
mapfile -t TEST_FILES < <(find test -name '*_test.exs' -not -path '*/support/*' | sort)

TOTAL="${#TEST_FILES[@]}"
if [ "$TOTAL" -gt "$FILE_CAP" ]; then
  echo "::warning::$TOTAL test files found, coverage capped at $FILE_CAP — $((TOTAL - FILE_CAP)) file(s) will publish no coverage entry this run."
fi

skipped=0
count=0
for f in "${TEST_FILES[@]}"; do
  if [ "$count" -ge "$FILE_CAP" ]; then break; fi
  count=$((count + 1))
  slug="$(echo "$f" | tr -c 'A-Za-z0-9' '_')"
  if MIX_ENV=test mix test "$f" --cover --export-coverage "$slug" >/dev/null 2>"/tmp/constat-cov-$slug.log"; then
    if [ -f "$COVER_DIR/$slug.coverdata" ]; then
      printf '%s\t%s\n' "$f" "$COVER_DIR/$slug.coverdata" >>"$MANIFEST"
    else
      echo "::warning::coverage run for $f produced no $COVER_DIR/$slug.coverdata — skipping"
      skipped=$((skipped + 1))
    fi
  else
    echo "::warning::coverage run failed for $f — skipping ($(tail -n1 "/tmp/constat-cov-$slug.log" 2>/dev/null))"
    skipped=$((skipped + 1))
  fi
done

mkdir -p "$(dirname "$OUTPUT_FILE")"
if [ -s "$MANIFEST" ]; then
  MIX_ENV=test mix run .github/scripts/constat_coverage_analyze.exs "$MANIFEST" "$OUTPUT_FILE"
else
  printf '{\n  "schema": "constat.check-coverage/v1",\n  "files": {}\n}\n' >"$OUTPUT_FILE"
  echo "no test file produced coverage data ($skipped skipped) — wrote an empty report to $OUTPUT_FILE"
fi
