// constat:template id=constat-runner-script version=24 sha256=8acbf843473fa8410c8943b2ac065b1c65e6cf2b120663d84359618508af6c44
// Generated by Constat. The runner: takes one queued attempt from Constat, runs the agent here, and
// reports back what it claims. Zero dependencies on purpose — this file must run on a bare Actions
// runner with nothing but Node and the Claude Code CLI installed by the workflow beside it.
//
// What this file may do is exactly three things, and the shape is the point: TAKE work, REPORT what
// the agent claims, and ASK whether it was told to stop. It never writes evidence — Constat collects
// that itself, afterwards, with its own credential — so nothing an agent does in here can mark its
// own homework.
import { spawn, execFileSync } from 'node:child_process';
import { chmodSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { createServer } from 'node:http';
import { randomBytes } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import { setTimeout as sleep } from 'node:timers/promises';

const CONSTAT_URL = (process.env.CONSTAT_URL ?? '').replace(/\/$/, '');
if (!CONSTAT_URL) fail('CONSTAT_URL is not set — the workflow names where Constat lives.');
// GitHub's own REST API, read from the variable Actions sets on every job: api.github.com on
// github.com, and the customer's own host on GitHub Enterprise. Never a constant of ours.
const GITHUB_API = (process.env.GITHUB_API_URL || 'https://api.github.com').replace(/\/$/, '');
const API = `${CONSTAT_URL}/api/v1`;
const STOP_POLL_MS = 30_000;
const REPORT_PATH = '.constat/report.json';

// A request that gets no HTTP answer at all — a network failure on the way out of this runner — is
// asked again, up to three times, ten seconds apart. A refusal (any HTTP status) is never retried:
// that is an answer. The travel test (4 September 2026) lost a whole wake to one bare "fetch failed"
// before anything was claimed, which on a quiet repository is hours until the next wake.
//
// EVERY request goes through here, and every request gets thirty seconds to answer. `fetch` has no
// timeout of its own: a hung connection never throws, so the retry below never fires and the job
// simply sits there. It did — a wake spent eleven minutes in the "Ask Constat" step on 4 September
// 2026 (finding 19) before a person cancelled it. A timeout is a network failure like any other:
// same catch, same warning naming the request, same three tries.
async function reach(what, url, init) {
  let last = null;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try { return await fetch(url, { ...init, signal: AbortSignal.timeout(30_000) }); }
    catch (err) {
      last = err;
      const why = err.name === 'TimeoutError' ? 'did not answer within 30 s' : `could not be reached: ${err.message}`;
      console.error(`::warning::${what} ${why} (try ${attempt} of 3)`);
      if (attempt < 3) await sleep(10_000);
    }
  }
  const why = last?.name === 'TimeoutError' ? 'no answer within 30 s' : (last?.message ?? 'no answer');
  throw new Error(`${what} could not be reached after 3 tries: ${why}`);
}

// ── identity: GitHub's own OIDC token for this job. Proves "Actions, in this repository". ──
async function oidcToken() {
  const url = process.env.ACTIONS_ID_TOKEN_REQUEST_URL;
  const req = process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN;
  if (!url || !req) throw new Error('No OIDC token is available. The job needs `permissions: id-token: write`.');
  const res = await reach('GitHub’s token mint', `${url}&audience=constat.io`, { headers: { authorization: `bearer ${req}` } });
  if (!res.ok) throw new Error(`GitHub would not mint an OIDC token: HTTP ${res.status}`);
  return (await res.json()).value;
}

async function constat(method, path, body) {
  // A fresh token per call: GitHub's OIDC tokens live about five minutes, and an attempt does not.
  // The first real run (1 Sep 2026) learned this at minute six, when a stop check was refused.
  const token = await oidcToken();
  const res = await reach('Constat', `${API}${path}`, {
    method,
    headers: { authorization: `Bearer ${token}`, ...(body ? { 'content-type': 'application/json' } : {}) },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const text = await res.text();
  let json = null;
  try { json = JSON.parse(text); } catch { /* not JSON */ }
  if (!res.ok) throw new Error(`Constat answered ${res.status} for ${method} ${path}: ${json?.error?.message ?? text}`);
  return json;
}

function fail(message) { console.error(`::error::${message}`); process.exit(1); }
function git(...args) { return execFileSync('git', args, { encoding: 'utf8' }).trim(); }

// ── GitHub, with the runner's OWN token ──
// Two ways to reach it, because two kinds of machine run this file. GitHub's own runners have the
// `gh` CLI on them; a machine of the customer's own (spec of 6 September 2026) very often does
// not, and until now every press of CI on such a machine failed with a warning nobody read and no
// CI run for Constat to witness. So: `gh` where it exists, and GitHub's REST API with the job's
// own token where it does not. Same token either way, and it never leaves this process.
let ghChecked = null;
function haveGh() {
  if (ghChecked === null) {
    try { execFileSync('gh', ['--version'], { stdio: 'ignore' }); ghChecked = true; }
    catch { ghChecked = false; console.log('The gh CLI is not on this machine; GitHub is reached through its REST API with this job\'s own token.'); }
  }
  return ghChecked;
}
async function github(method, path, body) {
  const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN || '';
  const repo = process.env.GITHUB_REPOSITORY || '';
  if (!token || !repo) return { ok: false, error: 'this job carries no GitHub token (GH_TOKEN) or repository name, and gh is not installed here' };
  let res;
  try {
    res = await reach('GitHub', `${GITHUB_API}/repos/${repo}${path}`, {
      method,
      headers: {
        authorization: `Bearer ${token}`, accept: 'application/vnd.github+json',
        'user-agent': 'constat-runner', ...(body ? { 'content-type': 'application/json' } : {}),
      },
      ...(body ? { body: JSON.stringify(body) } : {}),
    });
  } catch (err) { return { ok: false, error: err.message }; }
  const text = await res.text();
  let json = null; try { json = JSON.parse(text); } catch { /* not JSON */ }
  if (!res.ok) return { ok: false, error: `GitHub answered ${res.status}: ${json?.message ?? text.slice(0, 200)}` };
  return { ok: true, json };
}

// ── the default branch: asked of the REPOSITORY, never of whatever HEAD is on ──
//
// The wake of 6 September 2026, 20:38. A standing wake built an attempt and then, in the same job,
// took the release of Constat № 38. The attempt had left this working copy on its own branch, and
// the release read its base from `git rev-parse HEAD`: the runner merged the branch onto itself,
// reported the branch's own head as the merge commit, and pressed the release workflow on the
// attempt's branch — which the workflow rightly refused to deploy, since it deploys the default
// branch and nothing else. Nothing reached the default branch; a person merged and deployed by hand.
//
// So the base is asked of the remote itself: its HEAD is what "the default branch" means, it costs
// no token beyond the one this checkout already carries, and it is the same answer on GitHub
// Enterprise and on a machine of the customer's own. GitHub's record of the repository answers when
// the remote will not. What HEAD happens to be on is never an answer.
let theDefaultBranch = null;
async function defaultBranch() {
  if (theDefaultBranch) return theDefaultBranch;
  try {
    // "ref: refs/heads/main <tab> HEAD" — the remote's own words.
    const said = git('ls-remote', '--symref', 'origin', 'HEAD');
    const line = said.split('\n').map((l) => l.trim()).find((l) => l.startsWith('ref:'));
    const branch = line ? line.split(/\s+/)[1].replace(/^refs\/heads\//, '') : null;
    if (branch) { theDefaultBranch = branch; return branch; }
  } catch (err) {
    console.error(`::warning::the remote would not say which branch is the default one (${err.message}); asking GitHub instead.`);
  }
  const out = await github('GET', '');
  const named = out.ok ? out.json?.default_branch : null;
  if (typeof named === 'string' && named !== '') { theDefaultBranch = named; return named; }
  throw new Error(`could not tell which branch this repository's default one is: ${out.error ?? 'the remote said nothing'}`);
}

/** The repository's own workflows that a runner may press: never this one, never a release. */
function pressableWorkflows() {
  const dir = '.github/workflows';
  return (existsSync(dir) ? readdirSync(dir) : [])
    .filter((f) => /\.ya?ml$/.test(f) && f !== 'constat-runner.yml' && !/^constat-release/.test(f))
    .filter((f) => /^\s+workflow_dispatch:/m.test(readFileSync(`${dir}/${f}`, 'utf8')));
}

/** Has this workflow already run on this exact commit? Once per head commit, never twice. */
async function alreadyRan(f, ref, sha) {
  if (!sha) return false;
  if (haveGh()) {
    try {
      const runs = JSON.parse(execFileSync('gh', ['run', 'list', '--workflow', f, '--branch', ref, '--json', 'headSha,status', '--limit', '20'], { encoding: 'utf8' }));
      return Array.isArray(runs) && runs.some((r) => r.headSha === sha);
    } catch { return false; } // could not tell: press, as before
  }
  const out = await github('GET', `/actions/workflows/${f}/runs?branch=${encodeURIComponent(ref)}&per_page=20`);
  return out.ok && Array.isArray(out.json?.workflow_runs) && out.json.workflow_runs.some((r) => r.head_sha === sha);
}

/** Press one workflow's Run button on a branch. Returns null when it started, or why it did not. */
async function pressWorkflow(f, branch) {
  if (haveGh()) {
    try { execFileSync('gh', ['workflow', 'run', f, '--ref', branch], { stdio: 'inherit' }); return null; }
    catch (err) { return String(err.message).slice(0, 200); }
  }
  const out = await github('POST', `/actions/workflows/${f}/dispatches`, { ref: branch });
  return out.ok ? null : out.error;
}

/**
 * CI on a branch, at one commit. A push made with the workflow's own token never triggers
 * `push:` (GitHub's rule against runaway workflows), so the runner presses every Run button the
 * repository has. Without one, nothing runs and Constat will find no CI run to witness — said
 * loudly, here, rather than discovered later on an evidence screen with a hole in it.
 */
async function pressCiOn(branch, sha) {
  const files = pressableWorkflows();
  const dispatched = []; const pressed = []; const refused = [];
  for (const f of files) {
    if (await alreadyRan(f, branch, sha)) { dispatched.push(f); console.log(`${f} already ran on ${String(sha).slice(0, 7)}; not pressed again.`); continue; }
    const why = await pressWorkflow(f, branch);
    if (why) { refused.push(`${f}: ${why}`); console.error(`::warning::could not start ${f} on ${branch}: ${why}`); }
    else { dispatched.push(f); pressed.push(f); }
  }
  if (files.length === 0) console.error('::warning::no workflow declares workflow_dispatch, so CI will not run on the agent\'s branch and Constat will find no CI run to witness.');
  else if (dispatched.length === 0) console.error('::warning::CI was not started on the agent\'s branch, so Constat will find no CI run to witness. If the refusal above is HTTP 403, this workflow needs "actions: write" under permissions.');
  else if (pressed.length > 0) console.log(`Started on ${branch}: ${pressed.join(', ')}`);
  return { files, dispatched, pressed, refused };
}

// ── the standing wake: on a machine of your own, the runner asks for itself ──
//
// A wake is a cron GitHub fires loosely, and on a quiet repository not at all: on 6 September 2026
// a dispatched attempt sat queued for forty-five minutes until a person pressed Run. On GitHub's
// machines an ask every half-minute would be a bill; on a machine the customer already owns it is
// nothing but the loop this job runs in. So a project that named a runner of its own gets ONE
// long-lived job that asks Constat for work every thirty seconds, handles what it finds in the same
// order as any wake — the releases first, then an attempt — and presses its own Run when its shift
// is over, so the standing wake outlives the job that carries it.
//
// Each wake runs in a CHILD of this process: the same file, told by an argument to do one wake and
// end — an argument rather than a variable, because the agent's environment is an allow list built
// by hand here and nothing about this loop may add to the way environments are passed around. An
// attempt's mess — its working directory, its environment, whatever it left in memory, a crash —
// cannot then reach the next wake, and a wake that dies takes nothing down but itself.
const STANDING_SECONDS = Number(process.env.CONSTAT_STANDING_WAKE || 0);
const ONE_WAKE = process.argv.includes('--one-wake');
let wakeChild = null;

/** Another standing wake of this repository, already in progress: its run id, or null. */
async function standingWakeAlreadyUp() {
  const mine = Number(process.env.GITHUB_RUN_ID || 0);
  const out = await github('GET', '/actions/workflows/constat-runner.yml/runs?status=in_progress&per_page=30');
  if (!out.ok) {
    // Could not tell — and a runner that cannot tell must not stand down: the workflow's own
    // concurrency group already allows one run of it at a time, and standing down on a question
    // GitHub never answered would leave the repository with no wake at all.
    console.log(`Could not ask GitHub whether another standing wake is up (${out.error}); standing anyway — the workflow's concurrency group allows one at a time.`);
    return null;
  }
  const runs = Array.isArray(out.json?.workflow_runs) ? out.json.workflow_runs : [];
  // The OLDER one keeps the repository. Run ids only grow, so of any two that meet exactly one
  // stands down: a Run pressed while one is up is never a second wake, and a Run pressed while
  // none is up always starts one.
  const older = runs.filter((r) => Number(r.id) !== mine && (mine === 0 || Number(r.id) < mine));
  return older.length > 0 ? older[0].id : null;
}

/** One wake, in a child of this process: this same file, told to do a single wake and end. */
function oneWake() {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [fileURLToPath(import.meta.url), '--one-wake'], { stdio: 'inherit' });
    wakeChild = child;
    child.on('close', (code) => { wakeChild = null; resolve(code); });
    child.on('error', (err) => { wakeChild = null; console.error(`::warning::that wake could not be started: ${err.message}`); resolve(1); });
  });
}

/** The same directory, whatever a symlink or a trailing slash calls it. */
function samePath(a, b) {
  try { return realpathSync(a) === realpathSync(b); } catch { return resolvePath(a) === resolvePath(b); }
}

/**
 * Between one thing and the next: the working copy back where a fresh wake starts — the default
 * branch, fetched, at its tip, with nothing the wake before it left behind. On GitHub's machines
 * every wake is a new job with a new checkout and this is free; a standing wake has ONE working
 * copy for its whole shift, and an attempt ends standing on the branch it built, with its own
 * files and its own report on disk. The release that followed one on 6 September 2026 read that
 * branch as the default branch and merged it onto itself.
 */
async function backToTheDefaultBranch() {
  // NEVER a repository this script was not given. The wake resets a working copy hard — a forced
  // checkout of the default branch and a clean — and on 7 September 2026 the standing-wake checks
  // ran this script inside Constat's own repository during CI, which reset the ATTEMPT'S checkout
  // to the default branch half way through the suite. Every package that ran after that was tested
  // against the default branch instead of the attempt, and CI reported green on code it never ran.
  // The job's own workspace is the only tree a wake may touch, and GitHub names it.
  const workspace = process.env.GITHUB_WORKSPACE;
  if (!workspace || !samePath(process.cwd(), workspace)) {
    console.log(`Standing in ${process.cwd()}, which is not this job's workspace (${workspace ?? 'unset'}); the working copy is left exactly as it is.`);
    return;
  }
  try {
    const base = await defaultBranch();
    const wasOn = git('rev-parse', '--abbrev-ref', 'HEAD');
    const wasAt = git('rev-parse', 'HEAD');
    git('fetch', 'origin', base);
    git('checkout', '--force', '-B', base, `origin/${base}`);
    // Whatever the last wake left lying about, including the report file — which the next attempt
    // would otherwise read as its own and forward to Constat. Ignored files are left alone: an
    // installed node_modules is why the next wake is quick on a machine of your own.
    git('clean', '-ffd');
    rmSync(REPORT_PATH, { force: true });
    const at = git('rev-parse', 'HEAD');
    if (wasOn !== base || wasAt !== at) {
      console.log(`Back on ${base} at ${at.slice(0, 7)} for this wake (the one before it left ${wasOn} at ${wasAt.slice(0, 7)}).`);
    }
  } catch (err) {
    console.error(`::warning::the working copy could not be put back on the default branch before this wake: ${err.message}`);
  }
}

async function stand(everySeconds) {
  const alreadyUp = await standingWakeAlreadyUp();
  if (alreadyUp !== null) {
    console.log(`A standing wake is already running for this repository (run ${alreadyUp}); this one stands down. One at a time, or two agents share a branch.`);
    return;
  }
  const hours = Number(process.env.CONSTAT_STANDING_HOURS || 6);
  const endsAt = Date.now() + hours * 3_600_000;
  console.log(`The standing wake is up: asking Constat for work every ${everySeconds} s for the next ${hours} h. Nobody has to press anything.`);
  let stopping = false;
  const stop = () => { stopping = true; if (wakeChild) wakeChild.kill('SIGTERM'); };
  process.on('SIGTERM', stop);
  process.on('SIGINT', stop);
  while (!stopping && Date.now() < endsAt) {
    // A wake that failed said so in its own log; the standing wake asks again in thirty seconds
    // rather than ending the shift on it. An attempt takes as long as it takes, and the next ask
    // is the moment it is over.
    await backToTheDefaultBranch();
    const code = await oneWake();
    if (code !== 0) console.error(`::warning::that wake ended with exit code ${code}; asking again in ${everySeconds} s.`);
    if (stopping) break;
    await sleep(everySeconds * 1000);
  }
  if (stopping) { console.log('The standing wake was asked to stop, and has.'); return; }
  // The shift is over and this job is about to end, so it presses this workflow's own Run: the
  // concurrency group holds the new run until this one is gone, which is why the two never
  // overlap. If the press is refused, the schedule beside it wakes the runner within five minutes.
  const ref = process.env.GITHUB_REF_NAME || 'main';
  const pressed = await github('POST', '/actions/workflows/constat-runner.yml/dispatches', { ref });
  if (pressed.ok) console.log('The shift is over; this workflow pressed its own Run, so the standing wake carries on in a new job.');
  else console.error(`::warning::the standing wake could not press its own Run: ${pressed.error}. The schedule beside it wakes the runner within five minutes.`);
}

if (STANDING_SECONDS > 0 && !ONE_WAKE) {
  await stand(STANDING_SECONDS);
  process.exit(0);
}

// Whatever goes wrong after an attempt is taken, Constat hears about it: a record left "running"
// forever would hold the requirement and the Dispatch button with it. Last words, then exit.
let run = null; let child = null; let reported = false; let releaseTaken = null;
async function lastWords(err) {
  if (child && child.exitCode === null) child.kill('SIGTERM');
  const message = err instanceof Error ? err.message : String(err);
  console.error(`::error::${message}`);
  if (releaseTaken && !reported) {
    reported = true;
    try { await constat('POST', `/runner/releases/${releaseTaken.id}/finished`, { outcome: 'refused', reason: `the runner itself failed: ${message}`.slice(0, 300) }); }
    catch (e) { console.error(`::error::and could not tell Constat: ${e.message}`); }
  }
  if (run && !reported) {
    reported = true;
    try { await constat('POST', `/runner/runs/${run.id}/finished`, { outcome: 'failed', error: `The runner itself failed: ${message}` }); }
    catch (e) { console.error(`::error::and could not tell Constat: ${e.message}`); }
  }
  process.exit(1);
}
process.on('unhandledRejection', lastWords);
process.on('uncaughtException', lastWords);

// THE RELEASES FIRST, ALL OF THEM, and only then an attempt. A release is a merge — a minute —
// and an attempt is a build, up to an hour, with the whole wake behind it (wakes run one at a
// time). On 5 September 2026 the owner pressed Release on Constat № 23 at 22:19 and № 24 at 22:26;
// the wake at 22:27 asked for an attempt first, took one, and two judged, sealed releases sat
// behind an hour-long build. So: every queued release of this project, in the order they were
// pressed, each merged and reported before the next is asked for — a refusal is reported as a
// refusal and stops none of the others — and the attempt after them, exactly as before.
// Same doctrine as ever: this runner merges with ITS token and presses YOUR release workflow;
// Constat then witnesses the merge and the running app itself.
let releasesTaken = 0;
// A cap, not an expectation: Constat hands out one queued release at a time and never re-hands a
// reported one, so the queue empties. If it ever did not, a wake that merged for ever would be
// worse than one that stops and says so.
while (releasesTaken < 20) {
  const rel = await constat('POST', '/runner/release/claim');
  if (!rel?.release) break;
  releasesTaken += 1;
  await release(rel.release);
  // This release is answered for. The next one is a new one: nothing about it is reported yet, and
  // an attempt taken after it must be able to have its own last words (see lastWords above).
  releaseTaken = null; reported = false;
  if (releasesTaken === 20) console.error('::warning::twenty releases in one wake; the rest wait for the next one.');
}
if (releasesTaken > 0) console.log(`Took the releases first: ${releasesTaken} queued release(s) before asking for an attempt.`);

const claimed = await constat('POST', '/runner/claim');
if (!claimed?.run) { console.log(claimed?.waiting ?? 'Nothing queued.'); process.exit(0); }


async function release(r) {
  releaseTaken = r;
  console.log(`Took release of Constat № ${r.constatNumber}: ${r.branch} → the default branch.`);
  const report = async (body) => { reported = true; await constat('POST', `/runner/releases/${r.id}/finished`, body); };
  git('config', 'user.name', 'constat-runner'); git('config', 'user.email', 'runner@constat.io');
  // The base is the repository's default branch, never this working copy's HEAD: the wake before
  // this one may have been an attempt, and an attempt ends standing on a branch of its own.
  let base;
  try { base = await defaultBranch(); }
  catch (err) { await report({ outcome: 'refused', reason: String(err.message).slice(0, 300) }); return; }
  git('fetch', 'origin', r.branch, base);
  // And the merge starts ON that branch, at origin's tip, whatever this working copy was on a
  // moment ago. `--force`: an attempt's leftovers are not a reason to refuse a judged release.
  git('checkout', '--force', '-B', base, `origin/${base}`);
  // Merges the released branch onto the default branch, which is what this checkout now stands on.
  // Returns the CONFLICT line, or null when the merge is clean. One helper, because the merge has
  // to be doable again from a moved base without the two copies drifting apart.
  const mergeOnto = () => {
    try { git('merge', '--no-ff', `origin/${r.branch}`, '-m', `Release Constat № ${r.constatNumber}: ${r.title}`); return null; }
    catch (err) {
      try { git('merge', '--abort'); } catch { /* nothing to abort */ }
      return String(err.message).split('\n').find((l) => l.includes('CONFLICT')) ?? 'conflict';
    }
  };
  // A protected branch refuses the push for good. Open a pull request and say who has to click.
  const askAPerson = async (err) => {
    git('reset', '--hard', `origin/${base}`);
    let url = null;
    try {
      url = execFileSync('gh', ['pr', 'create', '--base', base, '--head', r.branch, '--title', `Release Constat № ${r.constatNumber}: ${r.title}`,
        '--body', 'Opened by the Constat runner: the default branch is protected, so a person must merge.'], { encoding: 'utf8' }).trim();
    } catch (prErr) {
      await report({ outcome: 'refused', reason: `the push to ${base} was refused and no pull request could be opened: ${String(prErr.message).slice(0, 160)}` });
      return;
    }
    await report({ outcome: 'waiting_for_person', pullRequestUrl: url, reason: String(err.message).slice(0, 200) });
  };
  const firstConflict = mergeOnto();
  if (firstConflict) {
    await report({ outcome: 'refused', reason: `the branch does not merge cleanly into ${base}: ${firstConflict}`.slice(0, 300) });
    return;
  }
  let mergeCommit = git('rev-parse', 'HEAD');
  // ${base} can move between the fetch above and the push below — another release landing first —
  // and git then refuses the push as not fast-forward. That is a race, not a verdict: fetch what
  // landed, merge onto it, push again, up to three times. (The travel test, 4 September 2026,
  // finding 14: Constat № 5 read "refused" at 09:16 because main had moved under it exactly once.)
  let movedUnderUs = null;
  for (let again = 0; again <= 3; again += 1) {
    if (again > 0) {
      console.error(`::warning::${base} moved under this release; fetching it again and merging again (try ${again} of 3).`);
      git('fetch', 'origin', base);
      git('reset', '--hard', `origin/${base}`);
      const conflict = mergeOnto();
      if (conflict) {
        await report({ outcome: 'refused', reason: `${base} moved under this release and the branch no longer merges cleanly into it: ${conflict}`.slice(0, 300) });
        return;
      }
      mergeCommit = git('rev-parse', 'HEAD');
    }
    try { git('push', 'origin', base); movedUnderUs = null; break; }
    catch (err) {
      // Both halves: git writes the rejection to stderr, and which of the two carries it depends
      // on how this process was spawned. A refusal read from the wrong stream would be retried as
      // a race forever, or sent to a person who cannot help.
      const message = `${err.message}
${err.stderr ?? ''}`;
      if (!/non-fast-forward|fetch first/i.test(message)) { await askAPerson(err); return; }
      movedUnderUs = message;
    }
  }
  if (movedUnderUs) {
    const line = movedUnderUs.split('\n').map((l) => l.trim()).find((l) => l.startsWith('!')) ?? movedUnderUs.split('\n')[0];
    await report({ outcome: 'refused', reason: `the push to ${base} was refused as not fast-forward, and merging again on a fresh fetch three times did not help: ${line}`.slice(0, 300) });
    return;
  }
  // Press the release workflow(s): every file named constat-release*.yml that declares workflow_dispatch.
  const dir = '.github/workflows';
  const files = (existsSync(dir) ? readdirSync(dir) : []).filter((f) => /^constat-release.*\.ya?ml$/.test(f) && /^\s+workflow_dispatch:/m.test(readFileSync(`${dir}/${f}`, 'utf8')));
  const workflow = { dispatched: false, file: files[0] ?? null, error: null };
  for (const f of files) {
    try { execFileSync('gh', ['workflow', 'run', f, '--ref', base], { stdio: 'inherit' }); workflow.dispatched = true; }
    catch (err) { workflow.error = String(err.message).slice(0, 200); }
  }
  if (files.length === 0) workflow.error = 'no workflow named constat-release*.yml declares workflow_dispatch';
  await report({ outcome: 'merged', mergeCommit, releaseWorkflow: workflow });
  console.log(`Merged as ${mergeCommit.slice(0, 7)}; release workflow ${workflow.dispatched ? 'pressed' : 'not pressed: ' + workflow.error}. Constat witnesses from here.`);
}
run = claimed.run;
// A tool this runner cannot run is refused as a failed attempt, in words — never a silent
// substitution of one tool for another. The catalogue on Constat's side moves with this script.
if (run.provider !== 'claude-code') {
  reported = true;
  await constat('POST', `/runner/runs/${run.id}/finished`, { outcome: 'failed', error: `this runner cannot run ${run.provider}; only claude-code is supported by this version of the runner script` });
  fail(`this runner cannot run ${run.provider}`);
}

// Only now, with an attempt in hand and a tool this runner can run, the repository's dependencies
// and the agent's CLI — the two installs the workflow used to run before asking. A failed install
// is reported as the attempt's failure (lastWords), never left as a wake that died in silence.
if (process.env.CONSTAT_INSTALL) {
  console.log(`Installing: ${process.env.CONSTAT_INSTALL}`);
  execFileSync('sh', ['-c', process.env.CONSTAT_INSTALL], { stdio: 'inherit' });
}
if (process.env.CONSTAT_AGENT_CLI) {
  execFileSync('npm', ['install', '-g', process.env.CONSTAT_AGENT_CLI], { stdio: 'inherit' });
}
console.log(`Took attempt ${run.id} (${run.provider} · ${run.model}); caps: $${run.envelope.budget_usd}, ${run.envelope.runtime_minutes} min.`);

// The credential: read from THIS environment by the name Constat recorded, and never sent
// anywhere. When the project named none, either of Claude Code's own names will do — an API key,
// or the token `claude setup-token` mints from a subscription. A secret the repository does not
// have arrives as an empty string, which is dropped so the agent never sees a blank credential.
const NATIVE_NAMES = ['ANTHROPIC_API_KEY', 'CLAUDE_CODE_OAUTH_TOKEN'];
for (const name of NATIVE_NAMES) if (!process.env[name]) delete process.env[name];
const keyName = run.credentialEnvVar ?? NATIVE_NAMES.find((name) => process.env[name]) ?? 'ANTHROPIC_API_KEY';
if (!process.env[keyName]) {
  const wanted = run.credentialEnvVar ? keyName : NATIVE_NAMES.join(' or ');
  reported = true;
  await constat('POST', `/runner/runs/${run.id}/finished`, {
    outcome: 'failed', error: `The repository secret ${wanted} is not set, so the agent could not start.`,
  });
  fail(`The repository secret ${wanted} is not set.`);
}
console.log(`Credential: ${keyName} (by name; its value stays here).`);

// ── the agent's environment: an ALLOW LIST, built here, never this process's own. ──
// Until 6 September 2026 the agent was started with the whole job environment. It carried the
// workflow's GH_TOKEN (contents and actions write), the OIDC request variables Constat's identity
// is minted from, where Constat lives, and every other secret the workflow passes in. On 5
// September at 18:51 the last thing an agent did before it ended was print all of it.
//
// The agent needs none of it. Everything done with those credentials happens in THIS process,
// after the agent has ended: the branch is pushed, CI is pressed, the run is reported. So the
// agent's environment is built from the names below — what a build needs, none of them a secret —
// plus the one credential the project named for it. Adding a name here is a deliberate act.
//
// Said plainly, because the line matters: HOME passes, so credentials that live on DISK under it
// (a gh login, git's own credential helper, the checkout's remote header) stay reachable by
// anything running as this user. This closes the environment; it does not sandbox the filesystem.
const AGENT_ENV_ALLOW = [
  // where programs live, where home is, who this is
  'PATH', 'HOME', 'USER', 'LOGNAME', 'SHELL',
  // where temporary files go, and what kind of terminal this is
  'TMPDIR', 'TEMP', 'TMP', 'TERM',
  // how text is encoded, what the clock says, and that this is CI — a test runner that opens a watch prompt hangs an attempt
  'LANG', 'LC_ALL', 'LC_CTYPE', 'TZ', 'CI',
  // the Node toolchain the workflow set up beside this script
  'NODE_OPTIONS', 'NVM_DIR', 'PNPM_HOME', 'COREPACK_HOME',
  // the JVM and Android toolchains an Expo or Gradle build needs
  'JAVA_HOME', 'ANDROID_HOME', 'ANDROID_SDK_ROOT', 'GRADLE_USER_HOME',
  // the Elixir toolchain
  'MIX_HOME', 'HEX_HOME',
];
const agentEnv = {};
for (const name of AGENT_ENV_ALLOW) if (process.env[name] !== undefined) agentEnv[name] = process.env[name];
// The credential, under the name Claude Code reads it by: its own when the project named one of
// the CLI's two names, ANTHROPIC_API_KEY otherwise. Exactly one auth channel goes in, so a machine
// login sitting in the job cannot be spent under a project credential's name.
agentEnv[NATIVE_NAMES.includes(keyName) ? keyName : 'ANTHROPIC_API_KEY'] = process.env[keyName];

git('config', 'user.name', 'constat-runner');
git('config', 'user.email', 'runner@constat.io');

// -- where the work starts from --
//
// It used to be the repository's default branch, always. Requirement of 8 September 2026: when an
// earlier attempt on the same requirement left a branch on the repository, this one starts from
// THAT branch, rebased onto the default branch first so it carries everything released since. On 7
// September 2026 the arrivals took four attempts and about $32, three of them rebuilding screens an
// earlier attempt had already made pass, because every attempt began at the default branch and
// inherited nothing but the refusal reason.
//
// Constat decides WHICH attempt -- it holds the record, and the branch it names is the one it
// ASSIGNED that attempt, never one an agent claimed. This decides whether the rebase actually
// applies, because that is a fact about git and only the machine holding the repository can find it
// out. When it does not apply, the attempt starts from the default branch exactly as before and the
// note says why: never a half-rebased working copy, and never silence about the fall-back.
//
// What does NOT move: the pull request is opened against the default branch, so the diff Constat
// shows and the verdict the judge signs are still measured against the whole of the work.
const theDefault = git('rev-parse', '--abbrev-ref', 'HEAD');
const theDefaultCommit = git('rev-parse', 'HEAD');
const short = (sha) => String(sha).slice(0, 7);
let baseBranch = theDefault;
let baseCommit = theDefaultCommit;
let startedFromRunId = null;
let startingPointNote = `Started from ${theDefault} at ${short(theDefaultCommit)}. ${run.startFromNote ?? ''}`.trim();
let startedFromLines = [];
const from = run.startFrom ?? null;
if (from && from.branch && from.commit) {
  // Back to the default branch, at its own tip, with nothing of the earlier attempt left behind.
  const backToTheDefault = (why) => {
    try { git('rebase', '--abort'); } catch { /* nothing to abort */ }
    git('checkout', '--force', '-B', theDefault, theDefaultCommit);
    git('clean', '-ffd');
    baseBranch = theDefault; baseCommit = theDefaultCommit; startedFromRunId = null;
    startingPointNote = `Started from ${theDefault} at ${short(theDefaultCommit)}: attempt ${from.number}'s branch ${from.branch} ${why}.`;
    startedFromLines = [
      `- Constat meant to start you from attempt ${from.number}'s branch \`${from.branch}\`, and could not: it ${why}.`,
      `- So this working copy is \`${theDefault}\` at \`${theDefaultCommit}\`, exactly as an attempt with nothing before it starts.`,
    ];
    console.error(`::warning::${startingPointNote}`);
  };
  try {
    git('fetch', 'origin', from.branch);
    const atOrigin = git('rev-parse', `origin/${from.branch}`);
    git('checkout', '--force', '-B', from.branch, atOrigin);
    git('clean', '-ffd');
    try {
      // Onto the default branch's tip: the earlier attempt's own commits, replayed on top of
      // everything released since it was built.
      git('rebase', theDefaultCommit);
      baseBranch = from.branch;
      // The commit that branch REACHED THE REPOSITORY at, not the local head the rebase just made:
      // a base an owner cannot go and look at is not a base anybody can check.
      baseCommit = atOrigin;
      startedFromRunId = from.runId;
      startingPointNote = `Started from attempt ${from.number} (branch ${from.branch} at ${short(atOrigin)}), `
        + `rebased onto ${theDefault} at ${short(theDefaultCommit)}. `
        + `The diff and the verdict are still measured against ${theDefault}.`;
      startedFromLines = [
        `- ${from.sentence ?? `This attempt starts from attempt ${from.number}.`}`,
        `- The work of attempt ${from.number} is already in this working copy: branch \`${from.branch}\` at \`${atOrigin}\`, rebased onto \`${theDefault}\` at \`${theDefaultCommit}\`. Do not rebuild it -- read it, and carry on from it.`,
        `- Your own branch still starts here, and your pull request is still opened against \`${theDefault}\`. The diff Constat shows and the verdict the judge signs are measured against \`${theDefault}\`, never against attempt ${from.number}.`,
      ];
      console.log(startingPointNote);
    } catch (err) {
      const conflict = String(err.message).split('\n').map((l) => l.trim()).find((l) => l.includes('CONFLICT'))
        ?? 'does not rebase cleanly';
      backToTheDefault(`does not rebase cleanly onto ${theDefault}: ${conflict}`.slice(0, 240));
    }
  } catch (err) {
    backToTheDefault(`could not be fetched from origin: ${String(err.message).split('\n')[0]}`.slice(0, 240));
  }
} else if (from) {
  console.error('::warning::Constat named an attempt to start from but gave no branch and commit; starting from the default branch.');
}

// The starting point, appended to the instruction the agent is handed. Appended rather than stored
// at dispatch because none of it is known then: the default branch's name comes from the remote,
// its tip from a fetch moments ago, and whether the earlier attempt's branch rebases at all is only
// answered by trying it. Every line is derived from what is written on the run, so the record --
// the stored instruction, plus base_branch, base_commit, started_from_run_id and the note -- says
// exactly what the agent was told.
const startingPoint = [
  '# Starting point (prepared by Constat, not by you)',
  `- This working copy is \`${baseBranch}\` at \`${baseCommit}\`, freshly fetched. Nothing of any other run remains in it.`,
  ...startedFromLines,
  `- Create your branch from here. To open your pull request against \`${theDefault}\`, run \`constat-pull-request\`: the runner opens it, once, with its own credential.`,
  '- Do NOT open a pull request against any other `constat/task-*` branch, even one you were started from: merging and deleting that branch would close yours unmerged.',
].join('\n');
// ── the map, where the machine already has it (requirement of 8 September 2026). ──
//
// The judged agent reads a repository the slow way: grep, then whole files, spending its context
// on lines it did not need. Where `graft` is already on THIS machine's PATH, the map of this
// working copy is built before the agent starts and the instruction gains one short section
// naming the tool and the four ways to ask it. Nothing else.
//
// Constat installs graft nowhere, on its own machine or anyone's, and none of graft's own wiring
// is used: no `graft init`, no hooks, no editor settings, no server of its own. A hook that timed
// out inside an attempt would read on the record as a red run whose cause is the harness, and that
// is exactly the distinction the run page was taught to draw.
//
// The build is capped in time and never fatal. If it fails, is slow, or the tool is a version that
// does not understand a flag, that is said in this log and the agent starts anyway: a map is a
// convenience, and an attempt is not allowed to die of one.
const GRAFT_CAP_MS = Number(process.env.CONSTAT_GRAFT_CAP_MS) || 120_000;
const THE_FOUR_ASKS = [
  '# The map of this repository is already built',
  '',
  '`graft` is on this machine and the map of this working copy was built before you started, so ask it',
  'instead of grepping and opening whole files. Four ways to ask, each answering from the map with exact',
  'file:line — no key, and nothing sent anywhere:',
  '',
  '- `graft ask "how does X work"` — a question about how something works, in plain words.',
  '- `graft grep <pattern>` — an exhaustive search, every hit grouped by the symbol enclosing it.',
  '- `graft skeleton <path>` — one file’s whole shape: its signatures, without their bodies.',
  '- `graft callers <symbol>` — who calls a symbol.',
].join('\n');

/** Is graft on this machine at all? Never installed and never fetched — only found, or not. */
function haveGraft() {
  try { execFileSync('graft', ['--version'], { stdio: 'ignore', timeout: 30_000 }); return true; }
  catch { return false; }
}

/** The map in the working copy, before the agent starts — or one line saying why there is none. */
function buildTheMap() {
  if (!haveGraft()) return null;
  // The map is Constat's convenience, and it does not get to write a line into the repository's
  // own files: --no-gitignore and --no-ignore leave .gitignore and .ignore exactly as the customer
  // keeps them, and graft/ is kept out of the agent's diff the LOCAL way, in .git/info/exclude,
  // which is not tracked and is not the customer's to review.
  try {
    const exclude = '.git/info/exclude';
    const already = existsSync(exclude) ? readFileSync(exclude, 'utf8') : '';
    if (!already.includes('graft/')) {
      writeFileSync(exclude, already + '\n# Constat: the map built for this attempt is not the attempt\'s work.\ngraft/\n.ignore\n');
    }
  } catch { /* the map is built either way; the worst of it is an untracked directory */ }
  const at = Date.now();
  try {
    execFileSync('graft', ['build', '--no-gitignore', '--no-ignore', '.'], { stdio: 'inherit', timeout: GRAFT_CAP_MS });
  } catch (err) {
    const why = err.signal === 'SIGTERM' || err.code === 'ETIMEDOUT'
      ? 'it ran past its ' + Math.round(GRAFT_CAP_MS / 1000) + ' s cap'
      : String(err.message ?? err).split('\n')[0].slice(0, 200);
    console.error('::warning::graft is on this machine but the map could not be built: ' + why
      + '. The agent starts anyway, without it: a map is a convenience, and this attempt is not allowed to die of one.');
    return null;
  }
  console.log('Built the graft map of this working copy in ' + ((Date.now() - at) / 1000).toFixed(1)
    + ' s — the agent starts with it, and its instruction says so.');
  return THE_FOUR_ASKS;
}
const theMap = buildTheMap();

// A machine with no graft on it — or one whose map would not build — hands over exactly the words
// it handed over yesterday: the stored instruction and the starting point, and not one byte more.
const theInstruction = [run.instruction, startingPoint, ...(theMap ? [theMap] : [])].join('\n\n');

// The two names that are not the agent's to move: the default branch, and the branch it was
// started from -- an earlier attempt's, already judged or waiting to be.
const notTheAgentsBranch = [theDefault, baseBranch];
// The commit this working copy stood on when the agent was handed it. Never baseCommit, which after
// a rebase names a commit this HEAD does not descend from; this is what "the agent committed
// something" is counted from, below.
const startedAtCommit = git('rev-parse', 'HEAD');

// Claude Code warns when a workspace has not been "trusted" — an interactive dialog no CI runner
// will ever see. Trust is recorded the way the CLI itself records it, so the log stays clean and
// nobody reads a cosmetic warning as the agent being blocked (someone did, on the second real run).
try {
  const p = `${process.env.HOME}/.claude.json`;
  const cfg = existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : {};
  cfg.projects = { ...(cfg.projects ?? {}), [process.cwd()]: { ...(cfg.projects?.[process.cwd()] ?? {}), hasTrustDialogAccepted: true } };
  writeFileSync(p, JSON.stringify(cfg));
} catch { /* a warning in the log, nothing more */ }

// ── the runner's hands: a push and a press the agent can ask for. ──
//
// Since Constat № 33 the judged agent's environment holds no GitHub credential, and that is not
// going back: a witness's credential in the examined party's pocket makes every pulled row a
// claim. But the discipline the whole product rests on — push the check RED, before the code that
// makes it green — needs a push while the implementation does not exist yet, and the runner only
// pushed once, after the agent had ended. So every attempt's red rung was dark: not because the
// agent skipped it, but because nobody could push a failing check while it was still failing.
//
// The runner keeps the token, and lends the ACT. Two commands are written onto the agent's PATH
// for the length of this attempt — constat-push and constat-pull-request — and each is four lines
// that ask THIS process, over a loopback socket, to do the thing with its own credential. Nothing
// is added to the agent's environment but a directory on PATH: no token, no address of Constat,
// no OIDC variable. A hand, not a key.
//
// Capped, because a hand is not a blank cheque: a fixed number of pushes per attempt and one
// pull request, and past that the runner says so in words the agent can read. And every act is
// reported to Constat while the run is still running, with both halves on it — the runner's own
// act, at the agent's request — so the record never credits a push to the party that could not
// have made it, and never hides who asked for it.
const HAND_PUSHES = 20;
const HAND_PULL_REQUEST_TRIES = 3;
const handsLent = { push: 0, pull_request: 0 };
let openedPullRequest = null;
// One at a time: two shims answered at once would run two git pushes in the same checkout.
let handQueue = Promise.resolve();

/** Say what this runner did with its own hands, on the run, while the run is still running. */
async function tellConstat(act, fields) {
  try { await constat('POST', `/runner/runs/${run.id}/acts`, { act, ...fields }); }
  catch (err) { console.error(`::warning::could not tell Constat about the ${act} it made on the agent's request: ${err.message}`); }
}

async function lendPush() {
  const branch = git('rev-parse', '--abbrev-ref', 'HEAD');
  if (notTheAgentsBranch.includes(branch)) return [409, `You are still on ${branch}. Make your own branch first — the runner pushes the branch you are on, and never the default branch nor the one you were started from.`];
  if (handsLent.push >= HAND_PUSHES) {
    return [429, `The runner has already pushed ${handsLent.push} times for this attempt, which is all it lends per attempt. Keep committing: whatever is committed when you end is pushed once more.`];
  }
  handsLent.push += 1;
  try { git('push', '--set-upstream', 'origin', branch); }
  catch (err) {
    const why = `${err.message}\n${err.stderr ?? ''}`.split('\n').map((l) => l.trim()).find((l) => l !== '') ?? 'no reason given';
    await tellConstat('push', { branch, refused: why });
    return [502, `git refused the push: ${why}`];
  }
  const sha = git('rev-parse', 'HEAD');
  console.log(`Pushed ${branch} at ${sha.slice(0, 7)} — the runner's own act, at the agent's request.`);
  await tellConstat('push', { branch, commitSha: sha });
  const ci = await pressCiOn(branch, sha);
  if (ci.dispatched.length > 0) await tellConstat('ci_pressed', { branch, commitSha: sha, workflows: ci.dispatched });
  for (const why of ci.refused) await tellConstat('ci_pressed', { branch, commitSha: sha, refused: why });
  const said = ci.dispatched.length > 0
    ? `CI is running on it: ${ci.dispatched.join(', ')}.`
    : ci.refused.length > 0 ? `CI could not be started: ${ci.refused.join('; ')}`
    : 'No workflow here declares workflow_dispatch, so no CI run was started.';
  return [200, `Pushed ${branch} at ${sha.slice(0, 7)}. ${said}`];
}

async function lendPullRequest(title, body) {
  const branch = git('rev-parse', '--abbrev-ref', 'HEAD');
  if (notTheAgentsBranch.includes(branch)) return [409, `You are still on ${branch}. Make your own branch and commit first.`];
  // One attempt opens one pull request. Asked again, the runner hands back the same one rather
  // than opening a second against the same branch.
  if (openedPullRequest) return [200, `The pull request is already open, and one attempt opens one: ${openedPullRequest}`];
  if (handsLent.pull_request >= HAND_PULL_REQUEST_TRIES) return [429, 'The runner has tried to open the pull request as often as it will for one attempt. Carry on with your work; the branch is pushed either way.'];
  handsLent.pull_request += 1;
  try { git('push', '--set-upstream', 'origin', branch); } catch { /* it may be pushed already; the open below says so if not */ }
  const heading = typeof title === 'string' && title.trim() !== '' ? title.trim() : `Constat attempt on ${branch}`;
  const words = (typeof body === 'string' && body.trim() !== '' ? body.trim() + '\n\n' : '')
    + 'Opened by the Constat runner with its own credential, at the judged agent\'s request: the agent holds no GitHub credential of its own.';
  const opened = await openPullRequest(branch, heading, words);
  if (opened.error) {
    await tellConstat('pull_request', { branch, refused: opened.error });
    return [502, `The pull request could not be opened: ${opened.error}. Carry on — your commits are pushed, and this is on the record as the runner's refusal, not yours.`];
  }
  openedPullRequest = opened.url;
  console.log(`Opened ${openedPullRequest} — the runner's own act, at the agent's request.`);
  await tellConstat('pull_request', { branch, pullRequestUrl: openedPullRequest });
  return [200, `Opened the pull request: ${openedPullRequest}`];
}

/** `gh` where the machine has it, GitHub's REST API with the job's own token where it does not. */
async function openPullRequest(branch, title, body) {
  if (haveGh()) {
    try {
      const url = execFileSync('gh', ['pr', 'create', '--base', theDefault, '--head', branch, '--title', title, '--body', body], { encoding: 'utf8' }).trim();
      return { url: url.split('\n').filter((l) => l.startsWith('http')).pop() ?? url };
    } catch (err) { return { error: `${String(err.message).slice(0, 200)} ${String(err.stderr ?? '').slice(0, 200)}`.trim() }; }
  }
  const made = await github('POST', '/pulls', { title, head: branch, base: theDefault, body });
  if (made.ok) return { url: made.json?.html_url ?? null };
  // Already open is not a refusal: the runner hands back the one that exists.
  const existing = await github('GET', `/pulls?head=${encodeURIComponent((process.env.GITHUB_REPOSITORY || '').split('/')[0] + ':' + branch)}&state=open`);
  const found = existing.ok && Array.isArray(existing.json) ? existing.json[0]?.html_url ?? null : null;
  return found ? { url: found } : { error: made.error };
}

const handDir = mkdtempSync(join(tmpdir(), 'constat-hand-'));
const handSecret = randomBytes(24).toString('hex');
// A dir of its own with no package.json above it inherits Node's default; saying it here means the
// shims below are read the same way wherever TMPDIR happens to sit.
writeFileSync(join(handDir, 'package.json'), '{"type":"commonjs"}');
const handServer = createServer((req, res) => {
  let raw = '';
  req.on('data', (c) => { raw += String(c); });
  req.on('end', () => {
    const answer = (status, said) => { res.statusCode = status; res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ said })); };
    // The secret is written into the shims, not into the agent's environment: another job on the
    // same machine cannot ask this runner to push someone else's branch.
    if (req.headers['x-constat-hand'] !== handSecret) return answer(403, 'That is not this attempt’s hand.');
    let asked = {}; try { asked = JSON.parse(raw || '{}'); } catch { /* said below */ }
    handQueue = handQueue
      .then(() => (asked.act === 'push' ? lendPush()
        : asked.act === 'pull_request' ? lendPullRequest(asked.title, asked.body)
        : [400, 'The runner lends two hands: constat-push and constat-pull-request.']))
      .then(([status, said]) => answer(status, said))
      .catch((err) => answer(500, `The runner could not: ${err.message}`));
  });
});
await new Promise((resolve) => handServer.listen(0, '127.0.0.1', resolve));
handServer.unref();
const handPort = handServer.address().port;
const handShim = (act) => `#!/usr/bin/env node
// Written by the Constat runner for THIS attempt, and thrown away with it. It holds no credential:
// it asks the runner's own process — which holds the token — to do the act and prints what it says.
const http = require('node:http');
const args = process.argv.slice(2);
const value = (name) => { const i = args.indexOf('--' + name); return i >= 0 ? args[i + 1] : null; };
const payload = JSON.stringify({ act: '${act}', title: value('title'), body: value('body') });
const req = http.request({
  host: '127.0.0.1', port: ${handPort}, path: '/hand', method: 'POST',
  headers: { 'content-type': 'application/json', 'content-length': Buffer.byteLength(payload), 'x-constat-hand': '${handSecret}' },
}, (res) => {
  let raw = '';
  res.on('data', (d) => { raw += d; });
  res.on('end', () => {
    let said = raw;
    try { said = JSON.parse(raw).said ?? raw; } catch (e) { /* whatever it said */ }
    process.stdout.write(said + '\\n');
    process.exit(res.statusCode === 200 ? 0 : 1);
  });
});
req.setTimeout(600000, () => { req.destroy(new Error('the runner did not answer within ten minutes')); });
req.on('error', (err) => { process.stderr.write('the runner did not answer: ' + err.message + '\\n'); process.exit(1); });
req.end(payload);
`;
for (const [name, act] of [['constat-push', 'push'], ['constat-pull-request', 'pull_request']]) {
  writeFileSync(join(handDir, name), handShim(act));
  chmodSync(join(handDir, name), 0o755);
}
// The one thing the hand adds to the agent's environment: a directory on PATH.
agentEnv.PATH = `${handDir}${agentEnv.PATH ? `:${agentEnv.PATH}` : ''}`;
console.log('The runner\'s hands are on the agent\'s PATH: constat-push and constat-pull-request.');

// ── run the agent, with the caps enforced HERE, on the machine that is spending. ──
const startedAt = Date.now();
const runtimeMs = run.envelope.runtime_minutes * 60_000;
child = spawn('claude', [
  '-p', '--output-format', 'stream-json', '--verbose',
  '--model', run.model,
  '--max-budget-usd', String(run.envelope.budget_usd),
  '--permission-mode', 'bypassPermissions',
  '--dangerously-skip-permissions',
  theInstruction,
], { stdio: ['ignore', 'pipe', 'inherit'], env: agentEnv });

// The agent's stream, one JSON object per line: tool uses are echoed so a person watching the job
// sees the work move — a silent log reads as a blocked agent — and the final `result` line carries
// what the CLI says about its own run.
let result = null; let pending = '';
const hint = (input) => input?.file_path ?? input?.path ?? input?.command ?? input?.pattern ?? input?.description ?? '';
child.stdout.on('data', (d) => {
  pending += d;
  const lines = pending.split('\n'); pending = lines.pop() ?? '';
  for (const line of lines) {
    let msg; try { msg = JSON.parse(line); } catch { continue; }
    if (msg.type === 'result') result = msg;
    if (msg.type === 'assistant') {
      for (const block of msg.message?.content ?? []) {
        if (block.type === 'tool_use') console.log(`  → ${block.name} ${String(hint(block.input)).slice(0, 120)}`);
      }
    }
  }
});
let haltReason = null;
const finished = new Promise((resolve) => child.on('close', (code) => resolve(code)));

// The stop channel's reader: the owner presses Stop in Constat, this asks every 30 s, and honours
// it by ending the agent. Both halves of that fact are then on the record — theirs and ours.
const watcher = (async () => {
  while (child.exitCode === null) {
    if (Date.now() - startedAt > runtimeMs) { haltReason = 'runtime'; child.kill('SIGTERM'); return; }
    try {
      const { stop } = await constat('GET', `/runner/runs/${run.id}/stop`);
      if (stop) { haltReason = 'owner_stop'; child.kill('SIGTERM'); return; }
    } catch { /* a failed read is not a stop; asked again next tick */ }
    await sleep(STOP_POLL_MS);
  }
})();
const exitCode = await finished;
await watcher.catch(() => {});
// The hands are lent for the length of the attempt, and the attempt is over: nothing else can ask
// this runner to push anything from here on.
handServer.close();

// ── what the CLI said about its own run: cost and usage are the provider's own figures. ──
if (!result && pending.trim()) { try { const last = JSON.parse(pending); if (last.type === 'result') result = last; } catch { /* no result line */ } }
const usage = result?.usage ?? {};
const inputTokens = ['input_tokens', 'cache_creation_input_tokens', 'cache_read_input_tokens']
  .map((k) => usage[k]).filter((v) => typeof v === 'number').reduce((a, b) => a + b, 0) || null;
// A cap crossed AFTER the work was finished is not a halt. On 4 September 2026 (finding 16, 17:06)
// an agent committed, wrote its report, and then spent eight cents more; the run was labelled
// halted, the requirement fell back to approved, and a finished report was thrown away. Two facts
// tell "finished, then overspent" from "stopped mid-work": commits beyond the base, and a report
// file on disk. With both, the work is there to be judged — so the outcome is `completed`, and the
// overrun is said in words instead of being the reason for discarding it. Without either — no
// commit, or no report — the cap really did stop the work, and halted stays.
const crossedCap = result?.subtype === 'error_max_budget_usd' || result?.subtype === 'error_max_turns';
let commitsBeyondBase = 0;
try { commitsBeyondBase = Number(git('rev-list', '--count', `${startedAtCommit}..HEAD`)) || 0; } catch { commitsBeyondBase = 0; }
const finishedFirst = crossedCap && commitsBeyondBase > 0 && existsSync(REPORT_PATH);
const spent = typeof result?.total_cost_usd === 'number' ? result.total_cost_usd : null;
const overBy = spent === null ? null : spent - run.envelope.budget_usd;
const overrunNote = overBy !== null && overBy > 0
  ? `finished, then crossed the cap by $${overBy.toFixed(2)} — its last commit and its report were already in place.`
  : `finished, then crossed the cap (${result?.subtype === 'error_max_turns' ? 'the turn limit' : 'the budget'}) — its last commit and its report were already in place.`;
if (!haltReason && crossedCap && !finishedFirst) haltReason = result?.subtype === 'error_max_budget_usd' ? 'budget' : 'max_turns';

// ── the agent's last words, for a run that ends with nothing to push. ──
// On 5 September 2026 at 18:51 an attempt read files for nine minutes, spent $3.23 and committed
// nothing. The record said it failed because "agent run ended: success" — the subtype of the CLI's
// result line, and nothing else. The exit code was 1 and the result line said is_error, and the
// agent's own last words were thrown away, so a usage limit, a refusal, and a connection cut off
// mid-turn all read the same. When there is no branch to push there is nothing else to look at, so
// everything the CLI said about its own ending is written on the run, as one sentence.
const firstLines = (text, howMany = 5, atMost = 600) => String(text)
  .split('\n').map((l) => l.trim()).filter((l) => l !== '')
  .slice(0, howMany).join(' ').slice(0, atMost);
const agentsLastWords = typeof result?.result === 'string' && result.result.trim() !== ''
  ? firstLines(result.result) : null;
const endedWithNothingToPush = () => {
  const cli = result
    ? `the CLI called it ${result.subtype ?? 'unknown'} (is_error: ${result.is_error ?? 'not said'})`
    : 'the CLI printed no result line';
  return `the agent ended with exit code ${exitCode} and no commit; ${cli}; `
    + (agentsLastWords ? `its last words: ${agentsLastWords}` : 'it left no last words');
};

// ── the agent's report: a CLAIM, forwarded whole. Constat parses it and records it as claims. ──
const report = existsSync(REPORT_PATH) ? JSON.parse(readFileSync(REPORT_PATH, 'utf8')) : null;

// Push whatever the agent committed, so CI can run on it and Constat can witness it. The branch
// name is the one the instruction assigned; if the agent never created it, there is nothing to push.
let branch = null; let commitSha = null; let prUrl = openedPullRequest ?? report?.pr_url ?? null;
try {
  branch = git('rev-parse', '--abbrev-ref', 'HEAD');
  // Neither the default branch nor the branch this attempt was STARTED from: the second is an
  // earlier attempt's, already judged or waiting to be, and pushing this attempt's work onto it
  // would rewrite the record of somebody else's.
  if (notTheAgentsBranch.includes(branch)) branch = null;
  else { git('push', '--set-upstream', 'origin', branch); commitSha = git('rev-parse', 'HEAD'); }
} catch (err) { console.error(`::warning::could not push the branch: ${err.message}`); }

// CI on the agent's branch, one last time — for whatever the agent committed and did not ask to
// have pushed. Never the release workflow: it deploys, and a branch is not released until a person
// has judged it and pressed Release. On 3 September 2026 this loop pressed constat-release on an
// attempt's branch and deployed unjudged code six minutes before its verdict.
//
// Once per head commit: the agent's own asking (constat-push) already pressed CI on every commit
// it pushed, and pressing again on the same commit only adds a duplicate run for Constat to
// choose between.
if (branch) await pressCiOn(branch, commitSha);

const outcome = haltReason ? 'halted' : (finishedFirst || (exitCode === 0 && result?.subtype === 'success')) ? 'completed' : 'failed';
await constat('POST', `/runner/runs/${run.id}/finished`, {
  outcome, haltReason, branch, commitSha, prUrl, baseBranch, baseCommit,
  startedFromRunId, startingPointNote,
  inputTokens, outputTokens: usage.output_tokens ?? null,
  estimatedCost: typeof result?.total_cost_usd === 'number' ? result.total_cost_usd : null,
  // A failed attempt WITH a branch has the branch, the diff and CI to be read; one without has
  // only what the CLI said, so that is what is written down.
  error: finishedFirst ? overrunNote
    : outcome !== 'failed' ? null
    : branch === null ? endedWithNothingToPush()
    : result?.subtype ? `agent run ended: ${result.subtype}` : `exit code ${exitCode}`,
  report,
});
reported = true;
console.log(`Reported ${outcome} for attempt ${run.id}. Constat will witness the branch on its next look.`);
