# constat:template id=elixir-coverage-analyze version=42 sha256=e0e4622df0e22aeb2753f2248a5b5196c317df1156fb2cf29ec6cf027ba8620d
# Generated by Constat's onboarding pull request. Reads the manifest constat-mix-coverage.sh
# wrote (one "test-file<TAB>coverdata-path" line per row) and writes the
# "constat.check-coverage/v1" JSON report every ecosystem's coverage collector produces.
#
# Usage: mix run constat_coverage_analyze.exs <manifestFile> <outputFile>

[manifest_path, output_file] = System.argv()

# `mix run` keeps on the code path only the applications this project lists (Elixir 1.15 and
# later), and :cover lives in OTP's :tools, which no project lists: put it back before it is used.
Mix.ensure_application!(:tools)
:cover.start()

q = <<34>>

json_string = fn value ->
  escaped =
    value
    |> to_string()
    |> String.replace(<<92>>, <<92, 92>>)
    |> String.replace(q, <<92>> <> q)
    |> String.replace(<<10>>, "\\n")

  q <> escaped <> q
end

rows =
  manifest_path
  |> File.read!()
  |> String.split("\n", trim: true)
  |> Enum.map(&String.split(&1, "\t"))

repo_root = File.cwd!()

files =
  for [test_file, coverdata_path] <- rows, into: %{} do
    :cover.reset()
    per_source =
      case :cover.import(String.to_charlist(coverdata_path)) do
        :ok ->
          # The modules the imported coverdata covers: nothing is cover-compiled in this run, so
          # :cover.modules() here is always empty.
          for mod <- :cover.imported_modules(), reduce: %{} do
            acc ->
              case :cover.analyse(mod, :calls, :line) do
                {:ok, entries} ->
                  lines =
                    entries
                    |> Enum.filter(fn {{_mod, line}, calls} -> calls > 0 and line > 0 end)
                    |> Enum.map(fn {{_mod, line}, _calls} -> line end)
                    |> Enum.uniq()
                    |> Enum.sort()

                  source =
                    case mod.module_info(:compile)[:source] do
                      nil -> nil
                      src -> src |> to_string() |> Path.relative_to(repo_root)
                    end

                  # Never the test module crediting itself with "coverage" of its own assertions —
                  # only PRODUCTION lines answer "does this check touch the change" — and never a
                  # path outside the repository (a dependency compiled elsewhere).
                  cond do
                    source == nil -> acc
                    lines == [] -> acc
                    String.starts_with?(source, "..") -> acc
                    String.starts_with?(source, "test/") -> acc
                    String.starts_with?(source, "deps/") -> acc
                    true -> Map.put(acc, source, lines)
                  end

                _ ->
                  acc
              end
          end

        {:error, reason} ->
          IO.warn("::warning::could not import #{coverdata_path} for #{test_file}: #{inspect(reason)}")
          %{}
      end

    {test_file, per_source}
  end
  |> Enum.reject(fn {_test_file, per_source} -> map_size(per_source) == 0 end)
  |> Map.new()

files_json =
  files
  |> Enum.map(fn {test_file, per_source} ->
    sources_json =
      per_source
      |> Enum.map(fn {source, lines} ->
        json_string.(source) <> ": [" <> Enum.join(lines, ", ") <> "]"
      end)
      |> Enum.join(",\n      ")

    json_string.(test_file) <> ": {\n      " <> sources_json <> "\n    }"
  end)
  |> Enum.join(",\n    ")

report =
  "{\n  " <> q <> "schema" <> q <> ": " <> q <> "constat.check-coverage/v1" <> q <>
    ",\n  " <> q <> "files" <> q <> ": {\n    " <> files_json <> "\n  }\n}\n"

File.mkdir_p!(Path.dirname(output_file))
File.write!(output_file, report)
IO.puts("wrote coverage for #{map_size(files)} test file(s) to #{output_file}")
