# constat:template id=exunit-formatter version=24 sha256=dfd535b703ec7a7569f779e81d7a717a80a08bf0d588514966c78dc1a2587763
defmodule Constat.CheckReportFormatter do
  @moduledoc """
  Writes ExUnit's own results as the machine-readable per-test report Constat's CI collector
  reads (schema `constat.check-report/v1`): one entry per test, its full name, and whether it
  passed, failed, or was skipped. ExUnit has no reporter that produces this on its own — this
  module is that reporter, generated by Constat's onboarding pull request.

  Enable it alongside the default formatter in `test/test_helper.exs`:

      ExUnit.configure(formatters: [ExUnit.CLIFormatter, Constat.CheckReportFormatter])
      ExUnit.start()

  Output path: `.constat/check-report/checks.json`, or `CONSTAT_CHECK_REPORT_PATH` if set.

  Before-code mode: if `CONSTAT_EXPECTED_REPORT` points at a JSON file (the report from a
  previous run of this SAME formatter), every name in that file which produced no result in
  THIS run is published as `could_not_run` instead of being silently absent — the same rule
  Constat's Node translator applies, so a test file that fails to even compile against the
  before-code reads as "did not run", never as "failed".
  """
  use GenServer

  def init(_opts), do: {:ok, %{checks: []}}

  def handle_cast({:test_finished, test}, state) do
    {:noreply, %{state | checks: [check_for(test) | state.checks]}}
  end

  def handle_cast({:suite_finished, _}, state) do
    write_report(Enum.reverse(state.checks))
    {:noreply, state}
  end

  def handle_cast(_event, state), do: {:noreply, state}

  defp check_for(%ExUnit.Test{name: name, module: module, state: test_state, tags: tags}) do
    status =
      case test_state do
        nil -> "passed"
        {:failed, _} -> "failed"
        {:skipped, _} -> "skipped"
        {:excluded, _} -> "skipped"
        {:invalid, _} -> "failed"
        _ -> "failed"
      end

    file =
      case Map.get(tags, :file) do
        nil -> nil
        path -> Path.relative_to_cwd(path)
      end

    test_description =
      name
      |> Atom.to_string()
      |> String.replace_prefix("test ", "")

    %{name: "#{inspect(module)} > #{test_description}", status: status, file: file}
  end

  defp write_report(checks) do
    published = project_onto_expected(checks)
    path = System.get_env("CONSTAT_CHECK_REPORT_PATH", ".constat/check-report/checks.json")
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, encode(published) <> "\n")
  end

  # No JSON library dependency on purpose: the schema this writes is small and fixed (a name, a
  # status, and an optional file, all plain strings), so hand-rolling encode/decode for exactly
  # that shape means this formatter works in any Elixir project without asking it to add a
  # dependency it may not already have. The quote character is built from its byte value
  # (<<34>>) rather than written as an escaped literal, so this generated source never has to
  # carry the doubled-up backslash escaping that makes hand-written JSON encoders hard to read.
  @q <<34>>

  defp encode(checks) do
    entries =
      checks
      |> Enum.map(fn %{name: name, status: status, file: file} ->
        file_json = if file, do: json_string(file), else: "null"

        "{" <> @q <> "name" <> @q <> ": " <> json_string(name) <>
          ", " <> @q <> "status" <> @q <> ": " <> json_string(status) <>
          ", " <> @q <> "file" <> @q <> ": " <> file_json <> "}"
      end)
      |> Enum.join(",\n    ")

    "{\n  " <> @q <> "schema" <> @q <> ": " <> @q <> "constat.check-report/v1" <> @q <>
      ",\n  " <> @q <> "checks" <> @q <> ": [\n    " <> entries <> "\n  ]\n}"
  end

  defp json_string(value) do
    backslash = <<92>>
    newline = <<10>>

    escaped =
      value
      |> to_string()
      |> String.replace(backslash, backslash <> backslash)
      |> String.replace(@q, backslash <> @q)
      |> String.replace(newline, backslash <> "n")

    @q <> escaped <> @q
  end

  defp project_onto_expected(checks) do
    case System.get_env("CONSTAT_EXPECTED_REPORT") do
      nil ->
        checks

      expected_path ->
        names =
          expected_path
          |> File.read!()
          |> extract_names()

        Enum.flat_map(names, fn name ->
          case Enum.filter(checks, &(&1.name == name)) do
            [] -> [%{name: name, status: "could_not_run", file: nil}]
            found -> found
          end
        end)
    end
  end

  # Pulls every `"name": "..."` value out of a checks.json this same formatter wrote, without a
  # JSON parser — the file's shape is under this module's own control, so a targeted regex is
  # enough. Assumes a test name carries no literal double-quote character, true of every
  # `describe > it` style name Constat has seen; a name that violates it is skipped rather than
  # mis-split, which only weakens the before-code comparison, never the head result.
  defp extract_names(content) do
    ~r/"name":\s*"([^"]*)"/
    |> Regex.scan(content)
    |> Enum.map(fn [_, name] -> name end)
    |> Enum.uniq()
  end
end
